apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rjang6i2z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rjang6i2z-go 
  name: rjang6i2z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rjang6i2z-go 
